### ISSUE TITLE
Database Design [Feature] 

### ISSUE THREAD

**Issue by ariIndu** [UTDallasEPICS/Reading-MLK#15]
**Feature Description**
Need to connect the web UI to a database with the users' information

**Requirements**
- Create the database model
- [Entity Relationship Diagram](https://miro.com/app/board/uXjVNvuzIxA=/?share_link_id=81761109134)
- allow the database to receive info from the sign up UI

**Comment by pariahGH** [comment]
https://github.com/UTDallasEPICS/Guides/blob/main/architecture_and_systems/users_roles_and_permissions.md
